[package]
name = "libtrusted"
version = "0.1.0"
authors = ["Paul Kirth <pk1574@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0"
